# Generated by Django 3.0.4 on 2020-04-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200416_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='titlepic',
            new_name='title',
        ),
    ]
