# Generated by Django 3.0.4 on 2020-04-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200416_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagname',
            field=models.CharField(default='post', max_length=30),
        ),
    ]
