# Generated by Django 3.0.4 on 2020-04-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post_tagname'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likescount',
            field=models.IntegerField(default=0),
        ),
    ]
