# Generated by Django 3.0.4 on 2020-04-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_post_likescount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likescount',
        ),
    ]
