# Generated by Django 3.0.4 on 2020-04-19 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='fullname unupdated', max_length=200, unique=True)),
                ('displayimage', models.ImageField(default='defaultprofilepic.png', null=True, upload_to='', verbose_name='')),
                ('status', models.CharField(default='status unupdated', max_length=140)),
                ('email', models.EmailField(default='email unupdated', max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
