# Generated by Django 3.0.4 on 2020-04-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200420_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='fullname',
        ),
        migrations.AddField(
            model_name='bio',
            name='firstname',
            field=models.CharField(default='Update bio', max_length=100),
        ),
        migrations.AddField(
            model_name='bio',
            name='lastname',
            field=models.CharField(default='Update bio', max_length=100),
        ),
        migrations.AlterField(
            model_name='bio',
            name='displayimage',
            field=models.ImageField(null=True, upload_to='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bio',
            name='status',
            field=models.TextField(max_length=140),
        ),
    ]
