# Generated by Django 3.0.4 on 2020-04-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200423_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='displayimage',
            field=models.ImageField(default='defaultprofilepic.png', null=True, upload_to='', verbose_name=''),
        ),
    ]
