# Generated by Django 3.0.4 on 2020-04-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200423_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='displayimage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=''),
        ),
    ]
