# Generated by Django 3.0.4 on 2020-04-18 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_auto_20200416_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
