# Generated by Django 3.0.4 on 2020-03-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='caption',
            field=models.CharField(default='caption', max_length=140),
        ),
    ]
