# Generated by Django 3.0.4 on 2020-03-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_workout_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='videofile',
            field=models.FileField(null=True, upload_to='media/', verbose_name=''),
        ),
    ]
