# Generated by Django 3.0.4 on 2020-03-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_auto_20200320_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='videofile',
            field=models.FileField(null=True, upload_to='', verbose_name=''),
        ),
    ]
