# Generated by Django 3.0.4 on 2020-03-21 10:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout', '0005_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='WComment',
        ),
    ]
