# Generated by Django 3.0.4 on 2020-04-20 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_auto_20200321_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='titlevid',
            new_name='title',
        ),
    ]
