# Generated by Django 3.0.4 on 2020-04-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_auto_20200420_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wcomment',
            name='body',
            field=models.TextField(max_length=140, null=True),
        ),
    ]
