# Generated by Django 3.0.4 on 2020-04-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='count',
        ),
    ]
