# Generated by Django 3.0.4 on 2020-04-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_remove_tag_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='likescount',
            field=models.IntegerField(default=0),
        ),
    ]
