# Generated by Django 3.0.4 on 2020-04-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_like_likescount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likescount',
        ),
    ]
