# Generated by Django 3.0.4 on 2020-04-20 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_remove_like_likescount'),
        ('feed', '0002_save'),
    ]

    operations = [
    ]
