# Generated by Django 3.0.5 on 2020-04-23 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0007_auto_20200421_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saves',
            name='saved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to=settings.AUTH_USER_MODEL),
        ),
    ]
