# Generated by Django 3.0.4 on 2020-04-23 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20200423_1213'),
        ('feed', '0008_auto_20200423_1451'),
    ]

    operations = [
    ]
